### ISSUE TITLE
consider using https://python-hvac.org/

### ISSUE THREAD

**Issue by singuliere** [peopledoc/vault-cli#44]
https://python-hvac.org/ would be a good replacement for `vault_cli/requests.py`. It implements a number of features that are non trivial to implement and that vault-cli is lacking (like client certificates, secrets v2 etc.)

**Comment by ewjoachim** [comment]
Hello :) Did you realize that we're already using hvac ? If you switch to the `hvac` backend with `vault --backend=hvac`, then it uses hvac instead of `requests` (which still ends up using requests, of course).

As main contributors of this package with @yannlachiver, we couldn't agree between using hvac and using request, so we've organized the lib so that we can use any of those. For now, we've only implemented the features we needed, but we could imagine adding more, and it's totally okay if some features are available only with the hvac backend.

Is there something you're missing as of now ? Feel free to throw in an issue or, if you're willing, a PR, I'd be happy to help :)

**Comment by singuliere** [comment]
> Hello :) Did you realize that we're already using hvac ?

No I did not :-) Taking another look then!

**Comment by singuliere** [comment]
Closing, sorry for the noise :-)

**Comment by ewjoachim** [comment]
No problem. We're only in beta and haven't had a lot of external users using this tool, so if you have any feedback, I'd be happy to hear it :)
